Provide separate v4 signature & hash tree for Play Signing
Play backend will serve signature & tree separately to Play client.
The in-memory signature & tree will be persisted in Spanner & Blobstore.

I tried to build the newest ApkSig in google3, got the following error:
third_party/java_src/apksig/src/main/java/com/android/apksig/internal/apk/v4/V4SchemeVerifier.java:149: error: [InsecureCryptoUsage] Insecure usage of a crypto API: the algorithm specification is not a compile-time constant expression. Please contact ise-crypto@ for assistance with this issue.
            publicKey = KeyFactory.getInstance(keyAlgorithm).generatePublic(
                                              ^
    (see http://go/bugpattern/InsecureCryptoUsage)
It might be something that need to be solved when apksig is sync'ed to
google3.

Test: A minor change that doesn't affect/break current test.

Bug: 153500952
Change-Id: I3b45b90c8c16481c990c42265a76d23d64fa5891